import type { AchievementStats, GameResult } from "../services/statsService";
import type { PowerUpKey } from "./powerUps";

export type RequirementType =
  | "total_wins"
  | "total_points"
  | "streak"
  | "mode_win"
  | "word_length"
  | "perfect_game"
  // Yeni tipler
  | "daily_streak" // günlük oyun serisi
  | "daily_total" // toplam günlük oyun
  | "blitz_speed" // saniye cinsinden hız
  | "blitz_wins"
  | "blind_wins"
  | "blind_level" // 1=yarı kör, 2=tam kör, 3=renksiz
  | "climb_level" // ulaşılan max seviye
  | "climb_wins"
  | "survival_words" // bir turda kaç kelime
  | "survival_wins"
  | "multi_sync_score" // senkronizasyon skoru (0-100)
  | "multi_wins"
  | "battle_wins"
  | "bomb_wins"
  | "bomb_survived_rounds" // bomba patlatmadan kaç tur
  | "total_games_played"
  | "total_words_solved"
  | "category_wins" // belirli kategoride kazanma
  | "win_streak";

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  requirementType: RequirementType;
  requirementValue: number;
  rewardPoints: number;
  rewardTitleId?: string;
  rewardPowerUp?: { id: PowerUpKey; quantity: number };
  rewardFrameId?: string;
  rewardNameTagId?: string;
  category: "general" | "expert" | "seasonal" | "secret";
  check: (stats: AchievementStats, lastGameResult?: GameResult) => boolean;
}

export const ACHIEVEMENTS: Achievement[] = [
  // ─── MEVCUT GENEL ───────────────────────────────────────────────
  {
    id: "first_win",
    title: "İlk Zafer",
    description: "İlk oyununu kazan.",
    icon: "trophy-outline",
    requirementType: "total_wins",
    requirementValue: 1,
    rewardPoints: 100,
    rewardTitleId: "title_rookie",
    category: "general",
    check: (stats, lastGameResult) => stats.totalWins >= 1,
  },
  {
    id: "winner_10",
    title: "On Numara",
    description: "Toplam 10 oyun kazan.",
    icon: "star-outline",
    requirementType: "total_wins",
    requirementValue: 10,
    rewardPoints: 500,
    rewardTitleId: "title_hunter",
    category: "general",
    check: (stats, lastGameResult) => stats.totalWins >= 10,
  },
  {
    id: "winner_50",
    title: "Yarım Dalya",
    description: "Toplam 50 oyun kazan.",
    icon: "ribbon-outline",
    requirementType: "total_wins",
    requirementValue: 50,
    rewardPoints: 2000,
    rewardPowerUp: { id: "hint", quantity: 5 },
    category: "general",
    check: (stats, lastGameResult) => stats.totalWins >= 50,
  },
  {
    id: "winner_100",
    title: "Şampiyon",
    description: "Toplam 100 oyun kazan.",
    icon: "medal-outline",
    requirementType: "total_wins",
    requirementValue: 100,
    rewardPoints: 5000,
    rewardTitleId: "title_champion",
    rewardFrameId: "frame_champion",
    rewardPowerUp: { id: "joker", quantity: 10 },
    category: "general",
    check: (stats, lastGameResult) => stats.totalWins >= 100,
  },

  // ─── YENİ GENEL ─────────────────────────────────────────────────
  {
    id: "games_played_50",
    title: "Düzenli Oyuncu",
    description: "Toplam 50 oyun oyna.",
    icon: "game-controller-outline",
    requirementType: "total_games_played",
    requirementValue: 50,
    rewardPoints: 300,
    rewardTitleId: "title_veteran",
    category: "general",
    check: (stats, lastGameResult) => stats.totalGames >= 50,
  },
  {
    id: "games_played_500",
    title: "Lexicon Bağımlısı",
    description: "Toplam 500 oyun oyna.",
    icon: "skull-outline",
    requirementType: "total_games_played",
    requirementValue: 500,
    rewardPoints: 3000,
    rewardTitleId: "title_obsessed",
    category: "general",
    check: (stats, lastGameResult) => stats.totalGames >= 500,
  },
  {
    id: "total_words_100",
    title: "Kelime Toplayıcı",
    description: "Toplam 100 kelime çöz.",
    icon: "book-outline",
    requirementType: "total_words_solved",
    requirementValue: 100,
    rewardPoints: 500,
    rewardTitleId: "title_lexicon",
    category: "general",
    check: (stats, lastGameResult) => stats.totalWordsSolved >= 100,
  },
  {
    id: "total_words_1000",
    title: "Sözlük",
    description: "Toplam 1000 kelime çöz.",
    icon: "library-outline",
    requirementType: "total_words_solved",
    requirementValue: 1000,
    rewardPoints: 5000,
    rewardTitleId: "title_godofwords",
    category: "general",
    check: (stats, lastGameResult) => stats.totalWordsSolved >= 1000,
  },
  {
    id: "win_streak_5",
    title: "Durdurulamaz",
    description: "5 oyunu üst üste kazan.",
    icon: "trending-up-outline",
    requirementType: "win_streak",
    requirementValue: 5,
    rewardPoints: 800,
    category: "general",
    check: (stats, lastGameResult) => stats.maxWinStreak >= 5,
  },
  {
    id: "win_streak_20",
    title: "Yenilmez",
    description: "20 oyunu üst üste kazan.",
    icon: "shield-checkmark-outline",
    requirementType: "win_streak",
    requirementValue: 20,
    rewardPoints: 8000,
    rewardPowerUp: { id: "shield", quantity: 15 },
    category: "expert",
    check: (stats, lastGameResult) => stats.maxWinStreak >= 20,
  },
  {
    id: "point_legend",
    title: "Efsane",
    description: "Toplam 250.000 puana ulaş.",
    icon: "diamond-outline",
    requirementType: "total_points",
    requirementValue: 250000,
    rewardPoints: 20000,
    rewardFrameId: "frame_diamond",
    rewardPowerUp: { id: "lightning", quantity: 20 },
    category: "expert",
    check: (stats, lastGameResult) => stats.totalPoints >= 250000,
  },

  // ─── GÜNLÜK MOD ─────────────────────────────────────────────────
  {
    id: "daily_first",
    title: "Güne İyi Başlangıç",
    description: "İlk günlük oyununu tamamla.",
    icon: "sunny-outline",
    requirementType: "daily_total",
    requirementValue: 1,
    rewardPoints: 100,
    rewardTitleId: "title_daily_first",
    category: "general",
    check: (stats, lastGameResult) => stats.dailyTotal >= 1,
  },
  {
    id: "daily_streak_7",
    title: "Haftanın Oyuncusu",
    description: "7 gün üst üste günlük oyunu çöz.",
    icon: "calendar-outline",
    requirementType: "daily_streak",
    requirementValue: 7,
    rewardPoints: 1000,
    rewardTitleId: "title_devoted",
    category: "general",
    check: (stats, lastGameResult) => stats.bestDailyStreak >= 7,
  },
  {
    id: "daily_streak_30",
    title: "Vazgeçmeyenler Kulübü",
    description: "30 gün üst üste günlük oyunu çöz.",
    icon: "infinite-outline",
    requirementType: "daily_streak",
    requirementValue: 30,
    rewardPoints: 10000,
    category: "general",
    check: (stats, lastGameResult) => stats.bestDailyStreak >= 30,
  },
  {
    id: "daily_streak_100",
    title: "Efsanevi Bağlılık",
    description: "100 gün üst üste günlük oyunu çöz.",
    icon: "planet-outline",
    requirementType: "daily_streak",
    requirementValue: 100,
    rewardPoints: 50000,
    rewardFrameId: "frame_galaxy",
    rewardPowerUp: { id: "time", quantity: 50 },
    category: "expert",
    check: (stats, lastGameResult) => stats.bestDailyStreak >= 100,
  },
  {
    id: "daily_total_50",
    title: "Sabah Ritüeli",
    description: "Toplam 50 günlük oyun oyna.",
    icon: "cafe-outline",
    requirementType: "daily_total",
    requirementValue: 50,
    rewardPoints: 2000,
    category: "general",
    check: (stats, lastGameResult) => stats.dailyTotal >= 50,
  },

  // ─── KLASİK MOD ─────────────────────────────────────────────────
  {
    id: "classic_win_first",
    title: "Klasiklere Dönüş",
    description: "Klasik modda ilk oyununu kazan.",
    icon: "trophy-outline",
    requirementType: "mode_win",
    requirementValue: 1,
    rewardPoints: 100,
    category: "general",
    check: (stats, lastGameResult) =>
      (stats.modeWins[lastGameResult?.mode || ""] || 0) >= 1,
  },
  {
    id: "classic_win_50",
    title: "Klasik Usta",
    description: "Klasik modda 50 oyun kazan.",
    icon: "medal-outline",
    requirementType: "mode_win",
    requirementValue: 50,
    rewardPoints: 3000,
    category: "general",
    check: (stats, lastGameResult) =>
      (stats.modeWins[lastGameResult?.mode || ""] || 0) >= 50,
  },
  {
    id: "perfect_classic_5",
    title: "İlk Denemede Beş",
    description: "Klasik modda 5 farklı kelimeyi ilk denemede bul.",
    icon: "flash-outline",
    requirementType: "perfect_game",
    requirementValue: 5,
    rewardPoints: 5000,
    rewardTitleId: "title_perfect",
    category: "expert",
    check: (stats, lastGameResult) => stats.perfectSolves >= 5,
  },
  {
    id: "classic_7letter",
    title: "Yedinci Kapı",
    description: "7 harfli bir kelimeyi klasik modda çöz.",
    icon: "key-outline",
    requirementType: "word_length",
    requirementValue: 7,
    rewardPoints: 1500,
    category: "expert",
    check: (stats, lastGameResult) =>
      (lastGameResult?.is_winner && (lastGameResult?.word_length || 0) >= 7) ||
      false,
  },
  {
    id: "classic_all_categories",
    title: "Çok Yönlü",
    description: "Her kategoride en az bir kez kazan.",
    icon: "grid-outline",
    requirementType: "category_wins",
    requirementValue: 1,
    rewardPoints: 3000,
    category: "expert",
    check: (stats, lastGameResult) =>
      [
        "karisik",
        "hayvanlar",
        "yemekler",
        "sehirler",
        "spor",
        "sanat",
        "bilim",
        "teknoloji",
        "tarih",
        "cografya",
        "edebiyat",
        "sinema",
      ].every((cat) => (stats.categoryWins[cat] || 0) >= 1),
  },

  // ─── BLİTZ MODU ─────────────────────────────────────────────────
  {
    id: "blitz_first",
    title: "Ilk Sprint",
    description: "Blitz modda ilk oyununu tamamla.",
    icon: "stopwatch-outline",
    requirementType: "blitz_wins",
    requirementValue: 1,
    rewardPoints: 150,
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["blitz"] || 0) >= 1,
  },
  {
    id: "blitz_under10",
    title: "Işık Hızı",
    description: "Bir kelimeyi 10 saniyenin altında çöz.",
    icon: "flash-outline",
    requirementType: "blitz_speed",
    requirementValue: 10,
    rewardPoints: 2000,
    rewardTitleId: "title_lightning",
    category: "expert",
    check: (stats, lastGameResult) => stats.bestBlitzSpeed <= 10,
  },
  {
    id: "blitz_under5",
    title: "Telekinezi",
    description: "Bir kelimeyi 5 saniyenin altında çöz.",
    icon: "rocket-outline",
    requirementType: "blitz_speed",
    requirementValue: 5,
    rewardPoints: 5000,
    rewardTitleId: "title_oracle",
    category: "expert",
    check: (stats, lastGameResult) => stats.bestBlitzSpeed <= 5,
  },
  {
    id: "blitz_wins_25",
    title: "Hız Tutkunu",
    description: "Blitz modda 25 oyun kazan.",
    icon: "speedometer-outline",
    requirementType: "blitz_wins",
    requirementValue: 25,
    rewardPoints: 3000,
    rewardTitleId: "title_sprinter",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["blitz"] || 0) >= 25,
  },

  // ─── KÖR MOD ────────────────────────────────────────────────────
  {
    id: "blind_first",
    title: "Cesur Başlangıç",
    description: "Kör modda ilk oyununu tamamla.",
    icon: "eye-off-outline",
    requirementType: "blind_wins",
    requirementValue: 1,
    rewardPoints: 300,
    rewardTitleId: "title_brave",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["blind"] || 0) >= 1,
  },
  {
    id: "blind_half",
    title: "Yarı Görür",
    description: "Yarı kör modda 10 oyun kazan.",
    icon: "eye-outline",
    requirementType: "blind_level",
    requirementValue: 1,
    rewardPoints: 1500,
    category: "expert",
    check: (stats, lastGameResult) => (stats.modeWins["blind"] || 0) >= 1,
  },
  {
    id: "blind_full",
    title: "Altıncı His",
    description: "Tam kör modda bir oyun kazan.",
    icon: "help-circle-outline",
    requirementType: "blind_level",
    requirementValue: 2,
    rewardPoints: 4000,
    rewardTitleId: "title_sixthsense",
    category: "expert",
    check: (stats, lastGameResult) => (stats.modeWins["blind"] || 0) >= 2,
  },
  {
    id: "blind_colorless",
    title: "Monokrom",
    description: "Renksiz modda bir oyun kazan.",
    icon: "contrast-outline",
    requirementType: "blind_level",
    requirementValue: 3,
    rewardPoints: 3000,
    rewardTitleId: "title_colorblind",
    category: "expert",
    check: (stats, lastGameResult) => (stats.modeWins["blind"] || 0) >= 3,
  },
  {
    id: "blind_wins_20",
    title: "Kör Şampiyon",
    description: "Kör modda toplam 20 oyun kazan.",
    icon: "ribbon-outline",
    requirementType: "blind_wins",
    requirementValue: 20,
    rewardPoints: 6000,
    category: "expert",
    check: (stats, lastGameResult) => (stats.modeWins["blind"] || 0) >= 20,
  },

  // ─── TIRMANMA MODU ──────────────────────────────────────────────
  {
    id: "climb_first",
    title: "Tırmanışa Başla",
    description: "Tırmanış modunda ilk oyununu tamamla.",
    icon: "arrow-up-outline",
    requirementType: "climb_wins",
    requirementValue: 1,
    rewardPoints: 200,
    rewardTitleId: "title_climber",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["climb"] || 0) >= 1,
  },
  {
    id: "climb_level_5",
    title: "Orta Yol",
    description: "Tırmanış modunda 5. seviyeye ulaş.",
    icon: "trending-up-outline",
    requirementType: "climb_level",
    requirementValue: 5,
    rewardPoints: 1000,
    category: "general",
    check: (stats, lastGameResult) => stats.maxClimbLevel >= 5,
  },
  {
    id: "climb_level_10",
    title: "Zirveye Yakın",
    description: "Tırmanış modunda 10. seviyeye ulaş.",
    icon: "mountain-outline",
    requirementType: "climb_level",
    requirementValue: 10,
    rewardPoints: 3000,
    category: "expert",
    check: (stats, lastGameResult) => stats.maxClimbLevel >= 10,
  },
  {
    id: "climb_summit",
    title: "Zirve Fatihi",
    description: "Tırmanış modunda en yüksek seviyeye ulaş.",
    icon: "flag-outline",
    requirementType: "climb_level",
    requirementValue: 20,
    rewardPoints: 10000,
    rewardTitleId: "title_summit",
    category: "expert",
    check: (stats, lastGameResult) => stats.maxClimbLevel >= 20,
  },

  // ─── HAYATTA KALMA ───────────────────────────────────────────────
  {
    id: "survival_first",
    title: "Hayatta Kalan",
    description: "Hayatta kalma modunda ilk oyununu tamamla.",
    icon: "heart-outline",
    requirementType: "survival_wins",
    requirementValue: 1,
    rewardPoints: 200,
    rewardTitleId: "title_survivor",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["survival"] || 0) >= 1,
  },
  {
    id: "survival_10words",
    title: "Milestone: 10",
    description: "Bir turda 10 kelime çöz.",
    icon: "checkmark-circle-outline",
    requirementType: "survival_words",
    requirementValue: 10,
    rewardPoints: 1000,
    category: "general",
    check: (stats, lastGameResult) => stats.maxSurvivalWords >= 10,
  },
  {
    id: "survival_20words",
    title: "Milestone: 20",
    description: "Bir turda 20 kelime çöz.",
    icon: "star-outline",
    requirementType: "survival_words",
    requirementValue: 20,
    rewardPoints: 3000,
    rewardTitleId: "title_endurance",
    category: "expert",
    check: (stats, lastGameResult) => stats.maxSurvivalWords >= 20,
  },
  {
    id: "survival_50words",
    title: "Ölümsüz",
    description: "Bir turda 50 kelime çöz.",
    icon: "infinite-outline",
    requirementType: "survival_words",
    requirementValue: 50,
    rewardPoints: 15000,
    rewardTitleId: "title_immortal",
    rewardPowerUp: { id: "extra", quantity: 10 },
    category: "expert",
    check: (stats, lastGameResult) => stats.maxSurvivalWords >= 50,
  },

  // ─── ÇOKLU MOD ───────────────────────────────────────────────────
  {
    id: "multi_first",
    title: "Paralel Düşünce",
    description: "Çoklu modda ilk oyununu tamamla.",
    icon: "copy-outline",
    requirementType: "multi_wins",
    requirementValue: 1,
    rewardPoints: 300,
    rewardTitleId: "title_multitasker",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["multi"] || 0) >= 1,
  },
  {
    id: "multi_sync_80",
    title: "Senkron",
    description: "Çoklu modda 80+ senkronizasyon skoru al.",
    icon: "git-merge-outline",
    requirementType: "multi_sync_score",
    requirementValue: 80,
    rewardPoints: 3000,
    category: "expert",
    check: (stats, lastGameResult) => stats.bestMultiSync >= 80,
  },
  {
    id: "multi_sync_100",
    title: "Mükemmel Uyum",
    description: "Çoklu modda 100 senkronizasyon skoru al.",
    icon: "pulse-outline",
    requirementType: "multi_sync_score",
    requirementValue: 100,
    rewardPoints: 8000,
    rewardTitleId: "title_sync",
    category: "expert",
    check: (stats, lastGameResult) => stats.bestMultiSync >= 100,
  },
  {
    id: "multi_wins_10",
    title: "Çok Görevli",
    description: "Çoklu modda 10 oyun kazan.",
    icon: "layers-outline",
    requirementType: "multi_wins",
    requirementValue: 10,
    rewardPoints: 2000,
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["multi"] || 0) >= 10,
  },

  // ─── DÜELLO & BOMBA ──────────────────────────────────────────────
  {
    id: "battle_first",
    title: "İlk Düello",
    description: "Battle modda ilk maçını kazan.",
    icon: "trophy-outline",
    requirementType: "battle_wins",
    requirementValue: 1,
    rewardPoints: 300,
    rewardTitleId: "title_duelist",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["battle"] || 0) >= 1,
  },
  {
    id: "battle_wins_10",
    title: "Arena Savaşçısı",
    description: "Battle modda 10 maç kazan.",
    icon: "shield-outline",
    requirementType: "battle_wins",
    requirementValue: 10,
    rewardPoints: 2000,
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["battle"] || 0) >= 10,
  },
  {
    id: "battle_wins_50",
    title: "Rakipsiz",
    description: "Battle modda 50 maç kazan.",
    icon: "trophy-outline",
    requirementType: "battle_wins",
    requirementValue: 50,
    rewardPoints: 10000,
    rewardTitleId: "title_unbeaten",
    category: "expert",
    check: (stats, lastGameResult) => (stats.modeWins["battle"] || 0) >= 50,
  },
  {
    id: "bomb_first",
    title: "Bombacı",
    description: "Bomba modda ilk oyununu tamamla.",
    icon: "nuclear-outline",
    requirementType: "bomb_wins",
    requirementValue: 1,
    rewardPoints: 300,
    rewardTitleId: "title_bomber",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["bomb"] || 0) >= 1,
  },
  {
    id: "bomb_5rounds",
    title: "Soğukkanlı",
    description: "Bomba modda 5 turu patlatmadan geç.",
    icon: "timer-outline",
    requirementType: "bomb_survived_rounds",
    requirementValue: 5,
    rewardPoints: 1500,
    rewardTitleId: "title_coldblood",
    category: "general",
    check: (stats, lastGameResult) => (stats.modeWins["bomb"] || 0) >= 5,
  },
  {
    id: "bomb_15rounds",
    title: "Bomba İmha Uzmanı",
    description: "Bomba modda 15 turu patlatmadan geç.",
    icon: "skull-outline",
    requirementType: "bomb_survived_rounds",
    requirementValue: 15,
    rewardPoints: 6000,
    rewardTitleId: "title_defuser",
    category: "expert",
    check: (stats, lastGameResult) => (stats.modeWins["bomb"] || 0) >= 15,
  },

  // ─── BOMBA EK ZORLU ─────────────────────────────────────────────
  {
    id: "bomb_wins_10",
    title: "Ateş Altında",
    description: "Bomba modda 10 oyun kazan.",
    icon: "flame-outline",
    requirementType: "bomb_wins",
    requirementValue: 10,
    rewardPoints: 2500,
    rewardTitleId: "title_fireproof",
    category: "general",
    check: (stats) => (stats.modeWins["bomb"] || 0) >= 10,
  },
  {
    id: "bomb_wins_25",
    title: "Bomba Ustası",
    description: "Bomba modda 25 oyun kazan.",
    icon: "nuclear-outline",
    requirementType: "bomb_wins",
    requirementValue: 25,
    rewardPoints: 8000,
    rewardTitleId: "title_bombmaster",
    category: "expert",
    check: (stats) => (stats.modeWins["bomb"] || 0) >= 25,
  },
  {
    id: "bomb_wins_50",
    title: "Bomba Efsanesi",
    description: "Bomba modda 50 oyun kazan.",
    icon: "skull-outline",
    requirementType: "bomb_wins",
    requirementValue: 50,
    rewardPoints: 20000,
    rewardPowerUp: { id: "shield", quantity: 20 },
    category: "expert",
    check: (stats) => (stats.modeWins["bomb"] || 0) >= 50,
  },

  // ─── BATTLE EK ZORLU ────────────────────────────────────────────
  {
    id: "battle_wins_25",
    title: "Savaş Makinesi",
    description: "Battle modda 25 maç kazan.",
    icon: "flash-outline",
    requirementType: "battle_wins",
    requirementValue: 25,
    rewardPoints: 5000,
    rewardTitleId: "title_warlord",
    category: "expert",
    check: (stats) => (stats.modeWins["battle"] || 0) >= 25,
  },
  {
    id: "battle_wins_100",
    title: "Efsane Savaşçı",
    description: "Battle modda 100 maç kazan.",
    icon: "trophy-outline",
    requirementType: "battle_wins",
    requirementValue: 100,
    rewardPoints: 30000,
    rewardTitleId: "title_legend",
    rewardFrameId: "frame_champion",
    rewardPowerUp: { id: "joker", quantity: 20 },
    category: "expert",
    check: (stats) => (stats.modeWins["battle"] || 0) >= 100,
  },
  {
    id: "battle_perfect",
    title: "Tek Hamle",
    description: "Battle modda kelimeyi ilk denemede bul.",
    icon: "rocket-outline",
    requirementType: "perfect_game",
    requirementValue: 1,
    rewardPoints: 5000,
    rewardTitleId: "title_onetap",
    category: "secret",
    check: (stats, lastGameResult) =>
      (lastGameResult?.mode === "battle" &&
        lastGameResult?.is_winner &&
        (lastGameResult?.attempts || 99) === 1) ||
      false,
  },

  // ─── GENEL EFSANE ────────────────────────────────────────────────
  {
    id: "winner_200",
    title: "Yenilmez",
    description: "Toplam 200 oyun kazan.",
    icon: "diamond-outline",
    requirementType: "total_wins",
    requirementValue: 200,
    rewardPoints: 15000,
    rewardTitleId: "title_invincible",
    category: "expert",
    check: (stats) => stats.totalWins >= 200,
  },
  {
    id: "winner_500",
    title: "Ölümsüz Şampiyon",
    description: "Toplam 500 oyun kazan.",
    icon: "planet-outline",
    requirementType: "total_wins",
    requirementValue: 500,
    rewardPoints: 50000,
    rewardTitleId: "title_immortal_champion",
    rewardFrameId: "frame_galaxy",
    rewardPowerUp: { id: "lightning", quantity: 30 },
    category: "expert",
    check: (stats) => stats.totalWins >= 500,
  },
  {
    id: "games_played_1000",
    title: "Bin Oyun",
    description: "Toplam 1000 oyun oyna.",
    icon: "infinite-outline",
    requirementType: "total_games_played",
    requirementValue: 1000,
    rewardPoints: 10000,
    rewardTitleId: "title_veteran_elite",
    category: "expert",
    check: (stats) => stats.totalGames >= 1000,
  },
  {
    id: "total_words_5000",
    title: "Yaşayan Sözlük",
    description: "Toplam 5000 kelime çöz.",
    icon: "library-outline",
    requirementType: "total_words_solved",
    requirementValue: 5000,
    rewardPoints: 25000,
    rewardTitleId: "title_wordgod",
    category: "expert",
    check: (stats) => stats.totalWordsSolved >= 5000,
  },
  {
    id: "win_streak_10",
    title: "Mükemmel Seri",
    description: "10 oyunu üst üste kazan.",
    icon: "trending-up-outline",
    requirementType: "win_streak",
    requirementValue: 10,
    rewardPoints: 3000,
    rewardTitleId: "title_streak",
    category: "expert",
    check: (stats) => stats.maxWinStreak >= 10,
  },
  {
    id: "win_streak_50",
    title: "Tanrı Modu",
    description: "50 oyunu üst üste kazan.",
    icon: "skull-outline",
    requirementType: "win_streak",
    requirementValue: 50,
    rewardPoints: 100000,
    rewardTitleId: "title_godmode",
    rewardFrameId: "frame_diamond",
    rewardPowerUp: { id: "joker", quantity: 50 },
    category: "secret",
    check: (stats) => stats.maxWinStreak >= 50,
  },
  {
    id: "point_god",
    title: "Puan Tanrısı",
    description: "Toplam 1.000.000 puana ulaş.",
    icon: "diamond-outline",
    requirementType: "total_points",
    requirementValue: 1000000,
    rewardPoints: 100000,
    rewardTitleId: "title_pointgod",
    category: "secret",
    check: (stats) => stats.totalPoints >= 1000000,
  },

  // ─── BLITZ EK ZORLU ─────────────────────────────────────────────
  {
    id: "blitz_under3",
    title: "Öngörü",
    description: "Bir kelimeyi 3 saniyenin altında çöz.",
    icon: "planet-outline",
    requirementType: "blitz_speed",
    requirementValue: 3,
    rewardPoints: 10000,
    rewardTitleId: "title_prophet",
    rewardPowerUp: { id: "lightning", quantity: 10 },
    category: "secret",
    check: (stats) => stats.bestBlitzSpeed <= 3,
  },
  {
    id: "blitz_wins_100",
    title: "Sprint Efsanesi",
    description: "Blitz modda 100 oyun kazan.",
    icon: "ribbon-outline",
    requirementType: "blitz_wins",
    requirementValue: 100,
    rewardPoints: 20000,
    rewardTitleId: "title_blitzking",
    category: "expert",
    check: (stats) => (stats.modeWins["blitz"] || 0) >= 100,
  },

  // ─── KÖR MOD EK ZORLU ──────────────────────────────────────────
  {
    id: "blind_wins_50",
    title: "Kör Efsane",
    description: "Kör modda toplam 50 oyun kazan.",
    icon: "planet-outline",
    requirementType: "blind_wins",
    requirementValue: 50,
    rewardPoints: 20000,
    rewardTitleId: "title_blindlegend",
    rewardPowerUp: { id: "hint", quantity: 20 },
    category: "secret",
    check: (stats) => (stats.modeWins["blind"] || 0) >= 50,
  },

  // ─── TIRMANMA EK ZORLU ──────────────────────────────────────────
  {
    id: "climb_wins_20",
    title: "Dağ Aşığı",
    description: "Tırmanış modunda 20 oyun kazan.",
    icon: "trending-up-outline",
    requirementType: "climb_wins",
    requirementValue: 20,
    rewardPoints: 8000,
    rewardTitleId: "title_mountaineer",
    category: "expert",
    check: (stats) => (stats.modeWins["climb"] || 0) >= 20,
  },
  {
    id: "climb_level_25",
    title: "Everest",
    description: "Tırmanış modunda 25. seviyeye ulaş.",
    icon: "flag-outline",
    requirementType: "climb_level",
    requirementValue: 25,
    rewardPoints: 25000,
    rewardTitleId: "title_everest",
    rewardFrameId: "frame_diamond",
    category: "secret",
    check: (stats) => stats.maxClimbLevel >= 25,
  },

  // ─── HAYATTA KALMA EK ZORLU ─────────────────────────────────────
  {
    id: "survival_wins_20",
    title: "Hayatta Kalmak Sanat",
    description: "Hayatta kalma modunda 20 oyun kazan.",
    icon: "heart-outline",
    requirementType: "survival_wins",
    requirementValue: 20,
    rewardPoints: 10000,
    rewardTitleId: "title_survivor_elite",
    category: "expert",
    check: (stats) => (stats.modeWins["survival"] || 0) >= 20,
  },
  {
    id: "survival_100words",
    title: "Sonsuz Güç",
    description: "Bir turda 100 kelime çöz.",
    icon: "infinite-outline",
    requirementType: "survival_words",
    requirementValue: 100,
    rewardPoints: 50000,
    rewardTitleId: "title_infinite",
    rewardPowerUp: { id: "extra", quantity: 25 },
    category: "secret",
    check: (stats) => stats.maxSurvivalWords >= 100,
  },

  // ─── GÜNLÜK MOD EK ZORLU ────────────────────────────────────────
  {
    id: "daily_streak_50",
    title: "Adanmış",
    description: "50 gün üst üste günlük oyunu çöz.",
    icon: "calendar-outline",
    requirementType: "daily_streak",
    requirementValue: 50,
    rewardPoints: 20000,
    rewardTitleId: "title_dedicated",
    rewardPowerUp: { id: "time", quantity: 30 },
    category: "expert",
    check: (stats) => stats.bestDailyStreak >= 50,
  },
  {
    id: "daily_streak_365",
    title: "Bir Yıl Boyunca",
    description: "365 gün üst üste günlük oyunu çöz.",
    icon: "planet-outline",
    requirementType: "daily_streak",
    requirementValue: 365,
    rewardPoints: 200000,
    rewardTitleId: "title_yearlong",
    rewardFrameId: "frame_galaxy",
    rewardPowerUp: { id: "lightning", quantity: 100 },
    category: "secret",
    check: (stats) => stats.bestDailyStreak >= 365,
  },

  // ─── GİZLİ / ÖZEL ───────────────────────────────────────────────
  {
    id: "perfect_classic_20",
    title: "Öngörücü",
    description: "Klasik modda 20 farklı kelimeyi ilk denemede bul.",
    icon: "eye-outline",
    requirementType: "perfect_game",
    requirementValue: 20,
    rewardPoints: 20000,
    rewardTitleId: "title_seer",
    category: "secret",
    check: (stats) => stats.perfectSolves >= 20,
  },
  {
    id: "all_modes_won",
    title: "Her Modda Kazanan",
    description: "Tüm oyun modlarında en az 1 kez kazan.",
    icon: "trophy-outline",
    requirementType: "mode_win",
    requirementValue: 1,
    rewardPoints: 15000,
    rewardTitleId: "title_allrounder",
    rewardPowerUp: { id: "joker", quantity: 15 },
    category: "secret",
    check: (stats) => {
      const modes = [
        "classic",
        "blitz",
        "daily",
        "blind",
        "climb",
        "survival",
        "multi",
        "battle",
        "bomb",
      ];
      return modes.every((m) => (stats.modeWins[m] || 0) >= 1);
    },
  },
  {
    id: "multi_wins_50",
    title: "Paralel Efsane",
    description: "Çoklu modda 50 oyun kazan.",
    icon: "layers-outline",
    requirementType: "multi_wins",
    requirementValue: 50,
    rewardPoints: 15000,
    rewardTitleId: "title_parallel",
    category: "expert",
    check: (stats) => (stats.modeWins["multi"] || 0) >= 50,
  },
];
